-- 用户表
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  nickname VARCHAR(100),
  bio TEXT,
  avatar TEXT,
  public_key TEXT,
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT
);

-- 好友请求表
CREATE TABLE IF NOT EXISTS friend_requests (
  id TEXT PRIMARY KEY,
  from_user VARCHAR(50) NOT NULL,
  to_user VARCHAR(50) NOT NULL,
  message TEXT,
  status VARCHAR(20) DEFAULT 'pending',
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
  FOREIGN KEY (from_user) REFERENCES users(username),
  FOREIGN KEY (to_user) REFERENCES users(username)
);

-- 好友关系表
CREATE TABLE IF NOT EXISTS friends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user1 VARCHAR(50) NOT NULL,
  user2 VARCHAR(50) NOT NULL,
  status VARCHAR(20) DEFAULT 'active',
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
  FOREIGN KEY (user1) REFERENCES users(username),
  FOREIGN KEY (user2) REFERENCES users(username),
  UNIQUE(user1, user2)
);

-- 消息表
CREATE TABLE IF NOT EXISTS messages (
  id TEXT PRIMARY KEY,
  from_user VARCHAR(50) NOT NULL,
  to_user VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  type VARCHAR(20) DEFAULT 'text',
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
  read BOOLEAN DEFAULT false,
  FOREIGN KEY (from_user) REFERENCES users(username),
  FOREIGN KEY (to_user) REFERENCES users(username)
);

-- 群组表
CREATE TABLE IF NOT EXISTS groups (
  id TEXT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  creator VARCHAR(50) NOT NULL,
  members TEXT[] NOT NULL,
  created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
  FOREIGN KEY (creator) REFERENCES users(username)
);

-- 动态表
CREATE TABLE IF NOT EXISTS tweets (
  id TEXT PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  cid TEXT,
  timestamp BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW()) * 1000)::BIGINT,
  FOREIGN KEY (username) REFERENCES users(username)
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_friend_requests_to ON friend_requests(to_user);
CREATE INDEX IF NOT EXISTS idx_friend_requests_status ON friend_requests(status);
CREATE INDEX IF NOT EXISTS idx_friends_user1 ON friends(user1);
CREATE INDEX IF NOT EXISTS idx_friends_user2 ON friends(user2);
CREATE INDEX IF NOT EXISTS idx_messages_from ON messages(from_user);
CREATE INDEX IF NOT EXISTS idx_messages_to ON messages(to_user);
CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp);
CREATE INDEX IF NOT EXISTS idx_groups_creator ON groups(creator);
CREATE INDEX IF NOT EXISTS idx_groups_members ON groups USING GIN(members);
CREATE INDEX IF NOT EXISTS idx_tweets_username ON tweets(username);
CREATE INDEX IF NOT EXISTS idx_tweets_timestamp ON tweets(timestamp);